### ISSUE TITLE
Q: is JavaFX8 supported?

### ISSUE THREAD

**Issue by 4ntoine** [gluonhq/client-samples#15]
I'm having some difficulties with building of graalvm native image for JavaFX8 app: https://github.com/oracle/graal/issues/403#issuecomment-508953600

Is JavaFX8 supported or it requires 12 min?

**Comment by jperedadnr** [comment]
The Gluon Client plugin uses Graal 20.0.0-ea, Java 11 and JavaFX 13-ea (see [default values](https://github.com/gluonhq/client-gradle-plugin#3-specify-plugin-extensions)).

While you can use the regular JavaFX 11+ SDK to run the project on a JVM, to build a native image the plugin makes use of a "customized" JavaFX SDK 13-ea, that uses static native libraries (as you can see in your ~/.gluon/omega folder when you run the samples on this repo), instead of the dynamic ones that are distributed within the regular SDK.
